id: I8B6D674A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-11-10T17:36:58+00:00'
last_modified: '2022-06-07T13:41:56.758956+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28949
  title: འབྲས་སྤུངས་དགོན་དུ་བཞུགས་སུ་གསོལ་བའི་དཔེ་རྙིང་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    2FCC:
      image_group_id: I1KG10818
      title: ''
      total_pages: 1386
      order: 1
      base_file: 2FCC.txt
    '4959':
      image_group_id: I1KG10819
      title: ''
      total_pages: 1142
      order: 2
      base_file: 4959.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
